# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9d37c894a963482f183740deb04b5bb7b7bf9d48f6a32a5dc69830f4dc23e2fe68a4377d58bc140669bb398939bb0453aed611732e52e8276d5d5115dc78e1b

test:
  secret_key_base: 1545c39b0145494f222de21103347fedd35b5cbc235bd0d00abcc85323aac99022e0ee790cf6c0ed73b6474f5e3c0ec98369c4c10c32fb9be0f67b92fdeed991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
